POST http://localhost:3000/items/search?skip=0&limit=9
content-type: application/json

{
    "itemName": "Shoe",
    "category": "Shoe",
    "origin": "China",
    "priceFrom": 1,
    "priceTo": 1000
}